/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _CfMETADATA {
  key: Generated<number | null>;
  value: Buffer | null;
}

export interface D1Migrations {
  applied_at: Generated<string>;
  id: Generated<number | null>;
  name: string | null;
}

export interface Events {
  ai_amount: number | null;
  ai_confidence: number | null;
  ai_currency: string | null;
  ai_date: string | null;
  ai_desc: string | null;
  ai_explain: string | null;
  ai_type: string | null;
  created_at: string;
  effective_at: string;
  event_id: string;
  prompt: string;
  status: string;
  updated_at: string;
  user_id: string;
}

export interface DB {
  _cf_METADATA: _CfMETADATA;
  d1_migrations: D1Migrations;
  events: Events;
}
